language: go

sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

env:
  - GO15VENDOREXPERIMENT=1

before_script:
  - go get github.com/mattn/goveralls

script: make test

after_success:
  - goveralls -service=travis-ci
